/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "pod-service-crd/pkg/apis/podservicecrd/v1alpha1"
	scheme "pod-service-crd/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodServicesGetter has a method to return a PodServiceInterface.
// A group's client should implement this interface.
type PodServicesGetter interface {
	PodServices(namespace string) PodServiceInterface
}

// PodServiceInterface has methods to work with PodService resources.
type PodServiceInterface interface {
	Create(*v1alpha1.PodService) (*v1alpha1.PodService, error)
	Update(*v1alpha1.PodService) (*v1alpha1.PodService, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PodService, error)
	List(opts v1.ListOptions) (*v1alpha1.PodServiceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodService, err error)
	PodServiceExpansion
}

// podServices implements PodServiceInterface
type podServices struct {
	client rest.Interface
	ns     string
}

// newPodServices returns a PodServices
func newPodServices(c *PodservicecrdV1alpha1Client, namespace string) *podServices {
	return &podServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podService, and returns the corresponding podService object, and an error if there is any.
func (c *podServices) Get(name string, options v1.GetOptions) (result *v1alpha1.PodService, err error) {
	result = &v1alpha1.PodService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodServices that match those selectors.
func (c *podServices) List(opts v1.ListOptions) (result *v1alpha1.PodServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PodServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podServices.
func (c *podServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a podService and creates it.  Returns the server's representation of the podService, and an error, if there is any.
func (c *podServices) Create(podService *v1alpha1.PodService) (result *v1alpha1.PodService, err error) {
	result = &v1alpha1.PodService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podservices").
		Body(podService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podService and updates it. Returns the server's representation of the podService, and an error, if there is any.
func (c *podServices) Update(podService *v1alpha1.PodService) (result *v1alpha1.PodService, err error) {
	result = &v1alpha1.PodService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podservices").
		Name(podService.Name).
		Body(podService).
		Do().
		Into(result)
	return
}

// Delete takes name of the podService and deletes it. Returns an error if one occurs.
func (c *podServices) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podService.
func (c *podServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodService, err error) {
	result = &v1alpha1.PodService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
