/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	podservicecrdv1alpha1 "pod-service-crd/pkg/apis/podservicecrd/v1alpha1"
	versioned "pod-service-crd/pkg/client/clientset/versioned"
	internalinterfaces "pod-service-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "pod-service-crd/pkg/client/listers/podservicecrd/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodServiceInformer provides access to a shared informer and lister for
// PodServices.
type PodServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodServiceLister
}

type podServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodServiceInformer constructs a new informer for PodService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodServiceInformer constructs a new informer for PodService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodservicecrdV1alpha1().PodServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodservicecrdV1alpha1().PodServices(namespace).Watch(options)
			},
		},
		&podservicecrdv1alpha1.PodService{},
		resyncPeriod,
		indexers,
	)
}

func (f *podServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podservicecrdv1alpha1.PodService{}, f.defaultInformer)
}

func (f *podServiceInformer) Lister() v1alpha1.PodServiceLister {
	return v1alpha1.NewPodServiceLister(f.Informer().GetIndexer())
}
