apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podservices.podservicecrd.k8s.io
spec:
  group: podservicecrd.k8s.io
  version: v1alpha1
  names:
    kind: PodService
    plural: podservices
    singular: podservice
    shortNames:
      - psc
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            deploymentName:
              type: string

